version: '3.8'

services:
  lb:
    image: nginx:1.16.0-alpine     
    depends_on:
      - www1
      - www2
    network_mode: host
    restart: always
    volumes:
      - ./nginx-lb/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-lb/error.log:/var/log/nginx/error.log 
      - ./certs:/etc/nginx/certs:ro
      - letsencrypt:/etc/letsencrypt:ro

  webhook:
    image: base-image:webhook
    ports:
      - 1080:80 
    restart: always
    env_file:
      - .env
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"      
    volumes:
      - ./nginx-webhook/sync.sh:/usr/local/bin/sync.sh:ro
      - ./nginx-webhook/nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./nginx-webhook/error.log:/var/log/nginx/error.log
      - ./:/usr/share/nginx/

  www1:
    image: nginx:1.16.0-alpine
    ports:
      - 1081:80 
    restart: always
    volumes:
      - ./nginx-www/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www/www1-error.log:/var/log/nginx/error.log
      - ./www/dist:/usr/share/nginx/html:ro

  www2:
    image: nginx:1.16.0-alpine
    ports:
      - 1082:80 
    restart: always
    volumes:
      - ./nginx-www/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-www/www2-error.log:/var/log/nginx/error.log
      - ./www/dist:/usr/share/nginx/html:ro

volumes:
  letsencrypt:
    external:
      name: letsencrypt_keys