version: '3'

services:
  lb:
    image: nginx:1.16.0-alpine
    depends_on:
      - www1
      - www2
    network_mode: host
    restart: always
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf:ro
      - ./lb-error.log:/var/log/nginx/error.log 
      - ./certs:/etc/nginx/certs
      - letsencrypt:/etc/letsencrypt:ro
  www1:
    image: nginx:1.16.0-alpine
    ports:
      - 1081:80 
    restart: always
    volumes:
      - ./nginx-www.conf:/etc/nginx/nginx.conf:ro
      - ./www/dist:/usr/share/nginx/html
      - ./www1-error.log:/var/log/nginx/error.log

  www2:
    image: nginx:1.16.0-alpine
    ports:
      - 1082:80 
    restart: always
    volumes:
      - ./nginx-www.conf:/etc/nginx/nginx.conf:ro
      - ./www/dist:/usr/share/nginx/html
      - ./www2-error.log:/var/log/nginx/error.log

volumes:
  letsencrypt:
    external:
      name: letsencrypt_keys